### ISSUE TITLE
Update for Nifi Version 2.0.0+

### ISSUE THREAD

**Issue by maveik** [bkosaraju/nifi-jira-bundle#3]
Hey,
are you planning to update your bundle for the new Nifi 2.0.0+ versions? I'm currently getting the following error:

> 2024-08-12 13:19:18,186 ERROR [main] org.apache.nifi.NiFi Failure to launch NiFi
java.lang.NoSuchMethodError: 'org.apache.nifi.components.PropertyDescriptor$Builder org.apache.nifi.components.PropertyDescriptor$Builder.allowableValues(org.apache.nifi.components.AllowableValue[])'
	at io.github.bkosaraju.processor.jiranotification.CreateJiraTicket.<clinit>(CreateJiraTicket.java:107)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.apache.nifi.nar.StandardExtensionDiscoveringManager.getClass(StandardExtensionDiscoveringManager.java:453)
	at org.apache.nifi.documentation.DocGenerator.documentConfigurableComponent(DocGenerator.java:116)
	at org.apache.nifi.documentation.DocGenerator.generate(DocGenerator.java:66)
	at org.apache.nifi.web.server.JettyServer.start(JettyServer.java:833)
	at org.apache.nifi.NiFi.<init>(NiFi.java:172)
	at org.apache.nifi.NiFi.<init>(NiFi.java:83)
	at org.apache.nifi.NiFi.main(NiFi.java:332)

That will be awesome. 
Best regards and thank you for your Work

**Comment by bkosaraju** [comment]
Hi @Maveik,

Will check on this weeks and try to patch it up ..
